name: Publish
on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Get release information
      run: |
        versionName=`sed -n 's/version = "\(.*\)"/\1/p' build.gradle.kts`
        export VERSION_NAME=$versionName
        echo "::set-env name=VERSION_NAME::$VERSION_NAME"
    - name: Publish with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      env:
        IS_GH_ACTION: true
        ORG_GRADLE_PROJECT_ghUsername: ${{ vars.GH_USERNAME }}
        ORG_GRADLE_PROJECT_ghToken: ${{ secrets.GH_TOKEN }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      with:
        arguments: publish
        gradle-version: 8.2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ env.VERSION_NAME }}
        release_name: v${{ env.VERSION_NAME }}
        body: See release notes
        draft: false
        prerelease: false
