name: Create Release
on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Get release information
        run: |
          versionName=`sed -n 's/version = "\(.*\)"/\1/p' build.gradle.kts`
          echo "VERSION_NAME=$versionName" >> "$GITHUB_ENV"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: v${{ env.VERSION_NAME }}
          body: See release notes
          draft: false
          prerelease: false
