name: Gradle Build Action
on:
  pull_request:
    branches: [ "master" ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      env:
        IS_GH_ACTION: true
        ORG_GRADLE_PROJECT_ghUsername: ${{ vars.GH_USERNAME }}
        ORG_GRADLE_PROJECT_ghToken: ${{ secrets.GH_TOKEN }}
      with:
        arguments: test
        gradle-version: 8.2
