name: Test
on:
  pull_request:
    branches: [ "master", "develop" ]
  push:
    branches: [ "develop" ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      env:
        IS_GH_ACTION: true
      with:
        arguments: test
        gradle-version: 8.2
